try on pwsh (#61)
* try on pwsh

* update pester version

* try without mac os

* try using my own random files

* use backslash

* debug env

* use .net method to get temp path

* debug folder creation

* need -Force for hidden folders

* do not fail fast

* print out env

* need a force delete

hidden folders need -force parameter on linux/mac

* change get-item().delete to remove-item

else the cmd.exe was used for deletion

* add a test around the link

* change handling of links on non windows platforms

* can not use $isWindows

* use $env:OS for determining windows

* use force for finding hidden path

* use new-item to create symlink

* revert old "if" change

* remove unused -force

* use new-item for linking

diff --git a/.github/workflows/pester.yml b/.github/workflows/pester.yml
--- a/.github/workflows/pester.yml
+++ b/.github/workflows/pester.yml
@@ -1,33 +1,35 @@
 name: Pester
 on: [push, pull_request, workflow_dispatch]
 jobs:
-  # test-pwsh:
-  #   strategy:
-  #     matrix:
-  #       platform: [ubuntu-latest, macos-latest, windows-latest]
-  #   runs-on: ${{ matrix.platform }}
-  #   steps:
-  #   - uses: actions/checkout@v4
-  #   - name: Run Pester tests (pwsh)
-  #     run: |
-  #       Write-host $PSVersionTable.PSVersion.Major $PSVersionTable.PSRemotingProtocolVersion.Minor
-  #       Install-Module -Name Pester -RequiredVersion 5.2.2 -Confirm:$false -Force
-  #       Set-Location -Path .\Tests\
-  #       Invoke-Pester
-  #       if ($Error[0].Fullyqualifiederrorid -eq 'PesterAssertionFailed') {exit 1}
-  #     shell: pwsh
+   test-pwsh:
+     strategy:
+       fail-fast: false
+       matrix:
+         platform: [ubuntu-latest, macos-latest, windows-latest]
+     runs-on: ${{ matrix.platform }}
+     steps:
+     - uses: actions/checkout@v4
+     - name: Run Pester tests (pwsh)
+       run: |
+         dir env:
+         Write-host $PSVersionTable.PSVersion.Major $PSVersionTable.PSRemotingProtocolVersion.Minor
+         Install-Module -Name Pester -RequiredVersion 5.6.1 -Confirm:$false -Force
+         Set-Location -Path .\Tests\
+         Invoke-Pester
+         if ($Error[0].Fullyqualifiederrorid -eq 'PesterAssertionFailed') {exit 1}
+       shell: pwsh
   
-  test-posh:
-    runs-on: windows-latest
-    steps:
-    - uses: actions/checkout@v4
-    - name: Run Pester tests (PowerShell)
-      run: |
-        Write-host $PSVersionTable.PSVersion.Major $PSVersionTable.PSRemotingProtocolVersion.Minor
-        Install-Module -Name Pester -RequiredVersion 5.6.1 -Confirm:$false -Force
-        $pesterConfig = New-PesterConfiguration
-        $pesterConfig.CodeCoverage.Enabled = $true
-        Set-Location -Path .\Tests\
-        Invoke-Pester -Configuration $pesterConfig
-        if ($Error[0].Fullyqualifiederrorid -eq 'PesterAssertionFailed') {exit 1}
-      shell: powershell
+   test-posh:
+     runs-on: windows-latest
+     steps:
+     - uses: actions/checkout@v4
+     - name: Run Pester tests (PowerShell)
+       run: |
+         Write-host $PSVersionTable.PSVersion.Major $PSVersionTable.PSRemotingProtocolVersion.Minor
+         Install-Module -Name Pester -RequiredVersion 5.6.1 -Confirm:$false -Force
+         $pesterConfig = New-PesterConfiguration
+         $pesterConfig.CodeCoverage.Enabled = $true
+         Set-Location -Path .\Tests\
+         Invoke-Pester -Configuration $pesterConfig
+         if ($Error[0].Fullyqualifiederrorid -eq 'PesterAssertionFailed') {exit 1}
+       shell: powershell
